comment: false
codecov:
  token: 8c56d87c-fdd6-415c-8d96-6bf8789927c6

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
